#!/bin/bash
#
# Envia la temperatura de la RaspBerry a OpenHab
#
#

temperatura=`/opt/vc/bin/vcgencmd measure_temp | sed 's/temp=\(.*\).C/\1/'`
curl -X PUT --header "Content-Type: text/plain" --header "Accept: application/json" -d "$temperatura" "http://192.168.24.6:8080/rest/items/RaspTemp1/state"
